/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wuD1g3lgUCc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";
import { RateForm } from "../form/RateForm";
import { Footer } from "../layouts/Footer";
import { Navbar } from "../layouts/Navbar";

export function Dashboard() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="bg-background py-12 md:py-24">
          <div className="container grid gap-8 md:grid-cols-2 md:gap-12">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Effortless Car Insurance Rates
              </h1>
              <p className="text-muted-foreground md:text-xl">
                Get personalized car insurance quotes in seconds with
                DriveRate.io. Our advanced algorithm considers your driving
                history, vehicle details, and location to find the best rates.
              </p>
              <p className="text-muted-foreground md:text-xl">
                Best of all, you don&apos;t need to sign up, give your email, or
                provide any identifying information. We value your privacy and
                make the process hassle-free.
              </p>
              <div className="flex flex-col gap-2 sm:flex-row">
                <Link
                  href="#"
                  className="inline-flex w-full items-center justify-center rounded-md border border-input bg-background px-8 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 sm:w-auto"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
            </div>
            <div>
              <RateForm />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
